#!/usr/bin/env ruby

require 'http'

class String
  # colorization
  def colorize(color_code)
    "\e[#{color_code}m#{self}\e[0m"
  end

  def red
    colorize(31)
  end

  def green
    colorize(32)
  end
end

class Smoketest
  def self.run!
    response = HTTP.get("http://localhost:3000/")
    if (response.code < 300)
      STDOUT.puts "Success!".green
      exit(0)
    end

    STDERR.puts "Request wasn't successful. Response code:".red, response.code
    exit(1)
  rescue HTTP::ConnectionError
    STDERR.puts "Connection Error, is the server running?".red
    exit(1)
  end
end

Smoketest.run!
