#!/usr/bin/env ruby

require 'net/http'

class String
  # colorization
  def colorize(color_code)
    "\e[#{color_code}m#{self}\e[0m"
  end

  def red
    colorize(31)
  end

  def green
    colorize(32)
  end
end

class Smoketest
  def self.run!
    # uri = URI('http://localhost:3000/graphql')
    # http = Net::HTTP.new(uri.host, uri.port)
    # request = Net::HTTP::Post.new(uri.path)
    # response = http.request(request)

    uri = URI('http://localhost:3000')
    response = Net::HTTP.get_response(uri)
    if (response.code.to_i < 300)
      STDOUT.puts "Success!".green
      exit(0)
    end

    STDERR.puts "Request wasn't successful. Response code:".red, response.code
    exit(1)
  rescue Errno::ECONNREFUSED
    STDERR.puts "Connection Refused! Is the server running?".red
    exit(1)
  end
end

Smoketest.run!
